/*
 * Provides commonroad obstacle shape data
 */

#ifndef COMMONROAD_DDS_SHAPE_IDL
#define COMMONROAD_DDS_SHAPE_IDL

//If a point does not exist in the commonroad representation, a default value of (0, 0) is chosen instead
struct CommonroadDDSPoint {
    double x;
    double y;
};

struct CommonroadDDSCircle {
    CommonroadDDSPoint center;
    double radius;
};

struct CommonroadDDSPolygon {
    sequence<CommonroadDDSPoint> points;
};

struct CommonroadDDSRectangle {
    double length;
    double width;
    CommonroadDDSPoint center;
    double orientation;
};

struct CommonroadDDSShape {
    sequence<CommonroadDDSCircle> circles;
    sequence<CommonroadDDSPolygon> polygons;
    sequence<CommonroadDDSRectangle> rectangles;
};
#endif