#include "TimeStamp.idl"

struct imagePoint
{
    double x;    // image coordinates in x direction
    double y;    // image coordinates in y direction
};

struct LedPoints 
{
    TimeStamp time_stamp;                // timestamp when the image was recorded
    sequence<imagePoint> led_points;     // image coordinates of detected led points
};
