#ifndef PARAMETER_IDL
#define PARAMETER_IDL
enum ParameterType 
{
    Invalid = 0,
    Bool,
    Int32,
    Double,
    String,
    Vector_Int32,
    Vector_Double
};

struct Parameter 
{
    string name; //@key
    ParameterType type;

    // Since weak typing is not supported, we reserve a member for each type.
    boolean value_bool;
    sequence<long>   values_int32;
    sequence<double> values_double;
    string value_string;
};
#endif