#include "TimeStamp.idl"

enum VehicleCommandMode
{
    DirectControlMode,
    SpeedCurvatureMode,
    TrajectoryMode
};

struct DirectControl 
{
    double motor_throttle;          // dimensionless, in [-1, 1]
    double steering_servo;          // dimensionless, in [-1, 1]
};

struct SpeedCurvature 
{
    double speed;       //    m/s
    double curvature;   //    1/meter
};

struct TrajectoryPoint 
{
    TimeStamp t;
    double px;  //  meter
    double py;  //  meter
    double vx;  //  m/s
    double vy;  //  m/s
};

union VehicleCommandData switch (VehicleCommandMode)
{
    case DirectControlMode:
        DirectControl direct_control;

    case SpeedCurvatureMode: 
        SpeedCurvature speed_curvature;

    case TrajectoryMode: 
        TrajectoryPoint trajectory_point;       
};


struct VehicleCommand 
{
    octet vehicle_id; //@key
    TimeStamp stamp;
    VehicleCommandData data;
};
