#include "TimeStamp.idl"

enum VehicleCommandMode
{
    DirectControlMode,
    SpeedCurvatureMode,
    TrajectorySegmentMode
};

struct DirectControl 
{
    double motor_throttle;          // dimensionless, in [-1, 1]
    double steering_angle;          // dimensionless, in [-1, 1] // TODO calibrate?
};

struct SpeedCurvature 
{
    double speed;       //    m/s
    double curvature;   //    1/meter
};

struct TrajectoryPoint 
{
    TimeStamp t;
    double px;  //  meter
    double py;  //  meter
    double vx;  //  m/s
    double vy;  //  m/s
};

struct TrajectorySegment 
{
    TrajectoryPoint start_point;
    TrajectoryPoint end_point;
};

union VehicleCommandData switch (VehicleCommandMode)
{
    case DirectControlMode:
        DirectControl directControl;

    case SpeedCurvatureMode: 
        SpeedCurvature speedCurvature;

    case TrajectorySegmentMode: 
        TrajectorySegment trajectorySegment;       
};


struct VehicleCommand 
{
    octet vehicle_id; //@key
    TimeStamp stamp;
    VehicleCommandData data;
};
