example;
codegen planTrajectory.prj;

load(fullfile('codegen','lib', 'planTrajectory','buildInfo.mat'))

% packNGo might miss the file MATLAB/R20xxx/sys/os/glnxa64/libstdc++.so.6
% If so, check the folder and make sure it is available for packNGo
packNGo(...
    buildInfo,...
    'packType', 'hierarchical', ...
    'fileName','port_gtf'...
);