#ifndef COLOR_IDL
#define COLOR_IDL

/**
 * \struct Color
 * \brief A color
 * \ingroup cpmlib_idl
 */
struct Color 
{
    octet a; //!< Alpha, between 0 and 255
    octet r; //!< Red, between 0 and 255
    octet g; //!< Green, between 0 and 255
    octet b; //!< Blue, between 0 and 255
};
#endif
