#include "Header.idl"
#include "Pose2D.idl"
#include "CommonroadDDSShape.idl"

#ifndef COMMONROAD_OBSTACLE_IDL
#define COMMONROAD_OBSTACLE_IDL

/**
 * \enum ObstacleType
 * \brief Possible types of obstacles, e.g. car or bicycle
 * \ingroup cpmlib_idl
 */
enum ObstacleType 
{
    Unknown=0,
    //Dynamic
    Car, 
    Truck, 
    Bus, 
    Motorcycle, 
    Bicycle, 
    Pedestrian, 
    PriorityVehicle, 
    Train,
    Taxi,
    //Static
    ParkedVehicle, 
    ConstructionZone, 
    RoadBoundary,
    //Environment
    Building,
    Pillar,
    MedianStrip
}; //Contains types of all obstacle types (dynamic, static, environment)

/**
 * \enum ObstacleClass
 * \brief Describes which obstacle class (w.r.t. Commonroad) an obstacle belongs to: Dynamic, Static, Environment
 * \ingroup cpmlib_idl
 */
enum ObstacleClass
{
    Dynamic,
    Static,
    Environment
};

/**
 * \struct CommonroadObstacle
 * \brief Provides data for simulated commonroad obstacles
 * \ingroup cpmlib_idl
 */
struct CommonroadObstacle {
    //! An ID can be set for each obstacle
    octet vehicle_id; //@key

    Header header; //!< There is no need to distinguish between create and valid after stamp in this case

    boolean is_moving; //!< Shows whether the obstacle is moving or not (moving /= dynamic or static obstacle, some obstacles are defined as dynamic but do not move)

    //! Pose contains vehicle orientation and position, but these values must not be exact
    Pose2D pose;

    //! Tells if values in pose are exact or only average values
    boolean pose_is_exact;

    //! The type of obstacle, e.g. car
    ObstacleType type;

    //! The obstacle class the obstacle belongs to (dynamic, static, environment)
    ObstacleClass obstacle_class;

    //! Optional value which defines a shape, especially useful if the occupancy type was used. But: also useful for visualizing lanelet references or inexact positional values
    CommonroadDDSShape shape; 

    double speed; //!< Speed in m/s
};
#endif