#ifndef HLC_HELLO_IDL
#define HLC_HELLO_IDL

/**
 * \struct HLCHello
 * \brief These messages are sent by the LCC to check if a program is still running on a remote machine
 * \ingroup cpmlib_idl
 */
struct HLCHello {
    string source_id; //!< To find out where the msg came from and to not answer to own msg

    boolean script_running; //!< If true, a Matlab / C++ session is still running
    boolean middleware_running; //!< If true, a Middleware session is still running
};
#endif