#include "Header.idl"

#ifndef VEHICLECOMMANDSPEEDCURVATURE_IDL
#define VEHICLECOMMANDSPEEDCURVATURE_IDL

/**
 * \struct VehicleCommandSpeedCurvature
 * \brief Used to send speed and curvature data to control a vehicle
 * 
 * SpeedCurvatureMode
 * 
 *     Uses a feedback controller to match the given reference speed.
 * 
 *     Uses a feedforward controller to steer along a path with the given curvature.
 * 
 *     This only works with "normal" driving, results may vary when spinning or sliding.
 * \ingroup cpmlib_idl
 */
struct VehicleCommandSpeedCurvature 
{
    //! ID of the vehicle to control
    octet vehicle_id; //@key

    //! Header information, e.g. to see if the msg is still valid
    Header header;

    double speed;       //!<    m/s
    double curvature;   //!<    1/meter
};
#endif