#include "Header.idl"

#ifndef VEHICLECOMMANDDIRECT_IDL
#define VEHICLECOMMANDDIRECT_IDL

/**
 * \struct VehicleCommandDirect
 * \brief Direct control commands that can be sent to the vehicle
 * 
 * Uses dimensionless, uncalibrated inputs and applies them directly to the motor and servo.
 * 
 * (motor_throttle ==  1) => Max forward
 * 
 * (motor_throttle ==  0) => Brake to standstill
 * 
 * (motor_throttle == -1) => Max reverse
 * 
 * (steering_servo ==  1) => Max left
 * 
 * (steering_servo ==  0) => Steering roughly centered, but may have an offset
 * 
 * (steering_servo == -1) => Max right
 * \ingroup cpmlib_idl
 */
struct VehicleCommandDirect 
{
    //! ID of the vehicle to control
    octet vehicle_id; //@key

    //! Header information, e.g. to see if the msg is still valid
    Header header;

    double motor_throttle;  //!< dimensionless, in [-1, 1]
    double steering_servo;  //!< dimensionless, in [-1, 1]
};
#endif