% searches fca message (starting at a given index)
function f_i = search_fca_index(DataFCA, time, vehicle_id, valid_stamp)
    f_i = 1;
    fca = DataFCA(f_i);
    while(~((int64(fca.header.valid_after_stamp.nanoseconds) < valid_stamp+10000 && ...
            int64(fca.header.valid_after_stamp.nanoseconds) > valid_stamp-10000 ) ...
            & (fca.vehicle_id == vehicle_id)) & (f_i <= numel(DataFCA)))
    f_i = f_i + 1;
        if(f_i <= numel(DataFCA))
            fca = DataFCA(f_i);
        else 
            disp(['Error: Message not found! ' ...
                'v_id: ' int2str(vehicle_id) ...
                ' valid_stamp: ' int2str(valid_stamp) ...
                ' time: ' int2str(time)]);
        end
    end
    disp(['v_id:' int2str(vehicle_id) ...
        ' FCA: ' int2str(fca.fca) ...
        ' f_i:' int2str(f_i) ...
        ' fca stamp: ' int2str(fca.header.valid_after_stamp.nanoseconds) ...
        ' time: ' int2str(time) ...
        ' valid_stamp: ' int2str(valid_stamp)])
end