# Makefile for the sntp_example program

PROGRAM=sntp_example
EXTRA_COMPONENTS = extras/sntp
ESPBAUD=921600
EXTRA_CFLAGS+=-DSNTP_DEBUG=LWIP_DBG_ON
#EXTRA_CFLAGS+=-DLWIP_DEBUG=1
include $(ESP_OPEN_RTOS_ROOT)/common.mk
