function main

    data = [ ... % Time(minutes), voltage
                    0         8.25   ; ...
                    18         8.05   ; ...
                    40         7.83   ; ...
                    60        7.68    ; ...
                    80        7.55    ; ...
                    101       7.47   ; ...
                    120       7.42   ; ...
                    140       7.35   ; ...
                    150       7.27   ; ...
                    160       7.22   ; ...
                    164       7.0   ; ...
                    167       6.8   ; ...
                    168       6.5   ; ...
                    169       6.4    ...
    ];
    

    clf
    box on
    plot(data(:,1), data(:,2))
    grid on
    xlabel('t [min]','FontSize',20)
    ylabel('Volt','FontSize',20)
    print('discharge_curve.png','-dpng')

    
end

