#include "VehicleState.idl"
#include "VehicleObservation.idl"

#ifndef VEHICLESTATELIST_IDL
#define VEHICLESTATELIST_IDL
//TODO rename
struct VehicleStateList {
    unsigned long long t_now;
    sequence<VehicleState> state_list;
    sequence<VehicleObservation> vehicle_observation_list;
};
#endif