% MIT License
% 
% Copyright (c) 2020 Lehrstuhl Informatik 11 - RWTH Aachen University
% 
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
% 
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.
% 
% This file is part of cpm_lab.
% 
% Author: i11 - Embedded Software, RWTH Aachen University

function main

%% measurement of large battery (current design, Sep 2020)

data = [ ... % Time(minutes), voltage
                  0       8.17   ; ... 
                 20       8.05   ; ...
                 40       7.97   ; ...
                 60       7.82   ; ...
                 80       7.72   ; ... 
                101       7.64  ; ... 
                120       7.56   ; ...
                140       7.48   ; ...
                150       7.46  ; ...
                160       7.42   ; ... 
                170       7.41    ; ... 
                180        7.39   ; ...
                190         7.37  ; ...
                200         7.36  ; ...
                210         7.36    ; ...
                220         7.35 ; ...
                230         7.35 ; ...
                240         7.35 ; ...
                260         7.32 ; ...
                280         7.27 ; ...
                300         7.18 ; ...
                310         7.07 ; ...
                320         6.93 ; ...
                323         6.88 ; ...
                326         6.85 ; ...
                329         6.80 ; ...
                322         6.72 ; ...
                325         6.62 ; ...
                327         6.53 ; ...
                329         6.45 ; ...
                330        6.37 ; ...
                331          6.29 ; ...
                332         6.28
                
];

    

    clf
    box on
    plot(data(:,1), data(:,2))
    grid on
    xlabel('t [min]','FontSize',20)
    ylabel('Volt','FontSize',20)
    print('discharge_curve.png','-dpng')

    
end

